# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

random_factor_decomp <- function(A_r, n, m, g_r, rank) {
    .Call('RandomFactorTensor_random_factor_decomp', PACKAGE = 'RandomFactorTensor', A_r, n, m, g_r, rank)
}

