# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

symmetric_tensor_decomp <- function(A_r, n, m, k, steps = 1000L, delta1 = 1E-2, delta2 = 1E-2, tol = 1E-8, loss_type = 1L, restrictCoreToDiag = TRUE) {
    .Call('TensorEmbedding_symmetric_tensor_decomp', PACKAGE = 'TensorEmbedding', A_r, n, m, k, steps, delta1, delta2, tol, loss_type, restrictCoreToDiag)
}

symmetric_tensor_decomp_cov <- function(A_r, X_r, n, m, k, steps = 1000L, lam = 10, delta1 = 1E-2, delta2 = 1E-2, tol = 1E-8, loss_type = 1L, restrictCoreToDiag = TRUE) {
    .Call('TensorEmbedding_symmetric_tensor_decomp_cov', PACKAGE = 'TensorEmbedding', A_r, X_r, n, m, k, steps, lam, delta1, delta2, tol, loss_type, restrictCoreToDiag)
}

