# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_bothproducts <- function(A_r, n, p, k) {
    .Call('TensorEmbedding_rcpparma_bothproducts', PACKAGE = 'TensorEmbedding', A_r, n, p, k)
}

